version: '3.9'

services:

  db:
    container_name: db
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nextjs_auth_login
    volumes:
      - ./db:/var/lib/postgresql/data